package sisjuridico.carbocat.enums;

public enum Court {
    STF,
    STJ,
    TST,
    TSE,
    STM,
    JUSTICA_ESTADUAL,
    JUSTICA_FEDERAL,
    JUSTICA_DO_TRABALHO,
    JUSTICA_ELEITORAL,
    JUSTICA_MILITAR_ESTADUAL,
    JUSTICA_MILITAR_DA_UNIAO,
    JUIZADO_ESPECIAL_CIVEL,
    JUIZADO_ESPECIAL_CRIMINAL,
    JUIZADO_ESPECIAL_FEDERAL,
    JUIZADO_ESPECIAL_DA_FAZENDA_PUBLICA,
    TURMA_RECURSAL,
    TURMA_REGIONAL_DE_UNIFORMIZACAO,
    TURMA_NACIONAL_DE_UNIFORMIZACAO,
    CNJ
}
