package sisjuridico.carbocat.enums;

public enum Nature {
    ADMINISTRATIVA,
    AMBIENTAL,
    DIREITO_CIVIL,
    CONSUMIDOR,
    CONTRATUAL,
    CRIMINAL,
    DIREITO_DE_FAMILIA,
    DIREITO_DO_TRABALHO,
    DIREITO_ELEITORAL,
    DIREITO_PREVIDENCIARIO,
    DIREITO_TRIBUTARIO,
    EMPRESARIAL,
    FAZENDA_PUBLICA,
    IMOBILIARIA,
    INFANCIA_E_JUVENTUDE,
    MILITAR,
    SUCESSOES
}
