package sisjuridico.carbocat.enums;

public enum Rit {
    PROCEDIMENTO_COMUM,
    PROCEDIMENTO_ESPECIAL,
    JUIZADO_ESPECIAL,
    SUMARIO,
    SUMARISSIMO,
    EXECUCAO,
    CUMPRIMENTO_DE_SENTENCA,
    TUTELA_PROVISORIA,
    PROCEDIMENTO_MONITORIO,
    PROCEDIMENTO_DE_JURISDICAO_VOLUNTARIA,
    PROCEDIMENTO_DE_INVENTARIO_E_PARTILHA,
    PROCEDIMENTO_DE_ACOES_DE_FAMILIA,
    PROCEDIMENTO_DE_ACOES_POSSESSORIAS,
    PROCEDIMENTO_DE_CONSIGNACAO_EM_PAGAMENTO,
    PROCEDIMENTO_DE_EXIGIR_CONTAS,
    PROCEDIMENTO_DE_EMBARGOS_DE_TERCEIRO
}
