spring:
  application:
    name: carbocat

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: ${JWT_EXPIRATION_SECONDS}
  refresh-token:
    expiration-seconds: ${REFRESH_TOKEN_EXPIRATION_SECONDS}

app:
  contract:
    expiration-cron: ${CONTRACT_EXPIRATION_CRON:0 0 0 * * *}
    expiration-zone: ${CONTRACT_EXPIRATION_ZONE:America/Bahia}
  refresh-token:
    cleanup-cron: ${REFRESH_TOKEN_CLEANUP_CRON:0 0 1 * * *}
  admin:
    name: ${ADMIN_NAME}
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
