

CREATE TABLE public.contract (
    id bigint NOT NULL,
    active boolean NOT NULL,
    advice_left_days integer,
    end_date date,
    file character varying(255) NOT NULL,
    obs character varying(255),
    original_end_date date,
    start_date date NOT NULL,
    type_contract character varying(255) NOT NULL,
    value numeric(12,2) NOT NULL,
    contracted_person_id bigint NOT NULL,
    contractor_person_id bigint NOT NULL,
    CONSTRAINT contract_type_contract_check CHECK (((type_contract)::text = ANY ((ARRAY['COMPRA_E_VENDA'::character varying, 'PRESTACAO_DE_SERVICOS'::character varying, 'LOCACAO'::character varying, 'COMODATO'::character varying, 'MUTUO'::character varying, 'DOACAO'::character varying, 'EMPREITADA'::character varying, 'MANDATO'::character varying, 'DEPOSITO'::character varying, 'FIANCA'::character varying, 'SEGURO'::character varying, 'TRANSPORTE'::character varying, 'SOCIEDADE'::character varying, 'FRANQUIA'::character varying, 'LICENCIAMENTO'::character varying, 'CESSAO_DE_DIREITOS'::character varying, 'CONFISSAO_DE_DIVIDA'::character varying, 'TRANSACAO'::character varying, 'CONTRATO_DE_TRABALHO'::character varying, 'CONTRATO_ADMINISTRATIVO'::character varying, 'CONCESSAO'::character varying, 'PERMISSAO'::character varying, 'CONVENIO'::character varying, 'TERMO_DE_FOMENTO'::character varying, 'TERMO_DE_COLABORACAO'::character varying, 'ACORDO_DE_COOPERACAO'::character varying])::text[])))
);

CREATE TABLE public.contract_extension (
    id bigint NOT NULL,
    extended_at date NOT NULL,
    new_end_date date NOT NULL,
    obs character varying(255),
    previous_end_date date NOT NULL,
    contract_id bigint NOT NULL
);

ALTER TABLE public.contract_extension ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contract_extension_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.contract ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contract_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.documents (
    id bigint NOT NULL,
    content_type character varying(255) NOT NULL,
    file_name character varying(255) NOT NULL,
    storage_path character varying(255) NOT NULL,
    contract_id bigint,
    lawsuit_id bigint,
    CONSTRAINT ck_documents_contract_or_lawsuit CHECK (((contract_id IS NOT NULL) <> (lawsuit_id IS NOT NULL)))
);

ALTER TABLE public.documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.lawsuit (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    court character varying(255) NOT NULL,
    data_inicio date NOT NULL,
    data_valor_causa date,
    initial_organization character varying(255) NOT NULL,
    nature character varying(255) NOT NULL,
    num_processo bigint NOT NULL,
    observacao character varying(2000),
    position_client character varying(255) NOT NULL,
    rit character varying(255) NOT NULL,
    valor_da_causa numeric(12,2),
    counter_part_lawyer_id bigint NOT NULL,
    counter_part_person_id bigint NOT NULL,
    lawyer_id bigint NOT NULL,
    person_id bigint NOT NULL,
    CONSTRAINT lawsuit_action_check CHECK (((action)::text = ANY ((ARRAY['ACAO_CIVIL_PUBLICA'::character varying, 'ACAO_CONSIGNATORIA'::character varying, 'ACAO_DE_ALIMENTOS'::character varying, 'ACAO_DE_COBRANCA'::character varying, 'ACAO_DE_EXECUCAO'::character varying, 'ACAO_DE_EXIGIR_CONTAS'::character varying, 'ACAO_DE_INDENIZACAO'::character varying, 'ACAO_DE_INVENTARIO'::character varying, 'ACAO_DE_OBRIGACAO_DE_FAZER'::character varying, 'ACAO_DE_REINTEGRACAO_DE_POSSE'::character varying, 'ACAO_DE_USUCAPIAO'::character varying, 'ACAO_DECLARATORIA'::character varying, 'ACAO_MONITORIA'::character varying, 'ACAO_POPULAR'::character varying, 'ACAO_RESCISORIA'::character varying, 'BUSCA_E_APREENSAO'::character varying, 'CUMPRIMENTO_DE_SENTENCA'::character varying, 'DIVORCIO_LITIGIOSO'::character varying, 'EMBARGOS_A_EXECUCAO'::character varying, 'EMBARGOS_DE_TERCEIRO'::character varying, 'EXECUCAO_DE_TITULO_EXTRAJUDICIAL'::character varying, 'EXECUCAO_FISCAL'::character varying, 'HABEAS_CORPUS'::character varying, 'MANDADO_DE_INJUNCAO'::character varying, 'MANDADO_DE_SEGURANCA'::character varying])::text[]))),
    CONSTRAINT lawsuit_court_check CHECK (((court)::text = ANY ((ARRAY['STF'::character varying, 'STJ'::character varying, 'TST'::character varying, 'TSE'::character varying, 'STM'::character varying, 'JUSTICA_ESTADUAL'::character varying, 'JUSTICA_FEDERAL'::character varying, 'JUSTICA_DO_TRABALHO'::character varying, 'JUSTICA_ELEITORAL'::character varying, 'JUSTICA_MILITAR_ESTADUAL'::character varying, 'JUSTICA_MILITAR_DA_UNIAO'::character varying, 'JUIZADO_ESPECIAL_CIVEL'::character varying, 'JUIZADO_ESPECIAL_CRIMINAL'::character varying, 'JUIZADO_ESPECIAL_FEDERAL'::character varying, 'JUIZADO_ESPECIAL_DA_FAZENDA_PUBLICA'::character varying, 'TURMA_RECURSAL'::character varying, 'TURMA_REGIONAL_DE_UNIFORMIZACAO'::character varying, 'TURMA_NACIONAL_DE_UNIFORMIZACAO'::character varying, 'CNJ'::character varying])::text[]))),
    CONSTRAINT lawsuit_initial_organization_check CHECK (((initial_organization)::text = ANY ((ARRAY['PRIMEIRO_GRAU'::character varying, 'SEGUNDO_GRAU'::character varying, 'TRIBUNAL_SUPERIOR'::character varying, 'JUIZADO_ESPECIAL'::character varying, 'TURMA_RECURSAL'::character varying, 'TURMA_REGIONAL_DE_UNIFORMIZACAO'::character varying, 'TURMA_NACIONAL_DE_UNIFORMIZACAO'::character varying, 'VARA_CIVEL'::character varying, 'VARA_CRIMINAL'::character varying, 'VARA_DE_FAMILIA'::character varying, 'VARA_DA_INFANCIA_E_JUVENTUDE'::character varying, 'VARA_DA_FAZENDA_PUBLICA'::character varying, 'VARA_DE_EXECUCOES_FISCAIS'::character varying, 'VARA_DE_EXECUCOES_PENAIS'::character varying, 'VARA_DO_TRABALHO'::character varying, 'ZONA_ELEITORAL'::character varying, 'AUDITORIA_MILITAR'::character varying, 'COMARCA'::character varying, 'FORO'::character varying, 'SECAO_JUDICIARIA'::character varying, 'SUBSECAO_JUDICIARIA'::character varying])::text[]))),
    CONSTRAINT lawsuit_nature_check CHECK (((nature)::text = ANY ((ARRAY['ADMINISTRATIVA'::character varying, 'AMBIENTAL'::character varying, 'DIREITO_CIVIL'::character varying, 'CONSUMIDOR'::character varying, 'CONTRATUAL'::character varying, 'CRIMINAL'::character varying, 'DIREITO_DE_FAMILIA'::character varying, 'DIREITO_DO_TRABALHO'::character varying, 'DIREITO_ELEITORAL'::character varying, 'DIREITO_PREVIDENCIARIO'::character varying, 'DIREITO_TRIBUTARIO'::character varying, 'EMPRESARIAL'::character varying, 'FAZENDA_PUBLICA'::character varying, 'IMOBILIARIA'::character varying, 'INFANCIA_E_JUVENTUDE'::character varying, 'MILITAR'::character varying, 'SUCESSOES'::character varying])::text[]))),
    CONSTRAINT lawsuit_num_processo_check CHECK ((num_processo >= 1)),
    CONSTRAINT lawsuit_position_client_check CHECK (((position_client)::text = ANY ((ARRAY['AUTOR'::character varying, 'REU'::character varying, 'REQUERENTE'::character varying, 'REQUERIDO'::character varying, 'EXEQUENTE'::character varying, 'EXECUTADO'::character varying, 'IMPETRANTE'::character varying, 'IMPETRADO'::character varying, 'APELANTE'::character varying, 'APELADO'::character varying, 'AGRAVANTE'::character varying, 'AGRAVADO'::character varying, 'EMBARGANTE'::character varying, 'EMBARGADO'::character varying, 'RECORRENTE'::character varying, 'RECORRIDO'::character varying, 'RECLAMANTE'::character varying, 'RECLAMADO'::character varying, 'CREDOR'::character varying, 'DEVEDOR'::character varying, 'INVENTARIANTE'::character varying, 'HERDEIRO'::character varying, 'TERCEIRO_INTERESSADO'::character varying, 'ASSISTENTE'::character varying, 'LITISCONSORTE'::character varying, 'AMICUS_CURIAE'::character varying])::text[]))),
    CONSTRAINT lawsuit_rit_check CHECK (((rit)::text = ANY ((ARRAY['PROCEDIMENTO_COMUM'::character varying, 'PROCEDIMENTO_ESPECIAL'::character varying, 'JUIZADO_ESPECIAL'::character varying, 'SUMARIO'::character varying, 'SUMARISSIMO'::character varying, 'EXECUCAO'::character varying, 'CUMPRIMENTO_DE_SENTENCA'::character varying, 'TUTELA_PROVISORIA'::character varying, 'PROCEDIMENTO_MONITORIO'::character varying, 'PROCEDIMENTO_DE_JURISDICAO_VOLUNTARIA'::character varying, 'PROCEDIMENTO_DE_INVENTARIO_E_PARTILHA'::character varying, 'PROCEDIMENTO_DE_ACOES_DE_FAMILIA'::character varying, 'PROCEDIMENTO_DE_ACOES_POSSESSORIAS'::character varying, 'PROCEDIMENTO_DE_CONSIGNACAO_EM_PAGAMENTO'::character varying, 'PROCEDIMENTO_DE_EXIGIR_CONTAS'::character varying, 'PROCEDIMENTO_DE_EMBARGOS_DE_TERCEIRO'::character varying])::text[])))
);


ALTER TABLE public.lawsuit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lawsuit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.lawyer (
    oab character varying(255),
    id bigint NOT NULL
);


--
-- Name: person; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.person (
    id bigint NOT NULL,
    cpf_cnpj character varying(255),
    name character varying(100) NOT NULL
);


--
-- Name: person_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    expiry_date timestamp(6) with time zone NOT NULL,
    token character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    password character varying(100) NOT NULL,
    role character varying(255) NOT NULL,
    user_name character varying(50) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying, 'ACCOUNTING'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contract_extension contract_extension_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contract_extension
    ADD CONSTRAINT contract_extension_pkey PRIMARY KEY (id);


--
-- Name: contract contract_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT contract_pkey PRIMARY KEY (id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- Name: lawsuit lawsuit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lawsuit
    ADD CONSTRAINT lawsuit_pkey PRIMARY KEY (id);


--
-- Name: lawyer lawyer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lawyer
    ADD CONSTRAINT lawyer_pkey PRIMARY KEY (id);


--
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: users ukk8d0f2n7n88w1a16yhua64onx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukk8d0f2n7n88w1a16yhua64onx UNIQUE (user_name);


--
-- Name: refresh_token ukr4k4edos30bx9neoq81mdvwph; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukr4k4edos30bx9neoq81mdvwph UNIQUE (token);


--
-- Name: person ukti43mpb7v4b6t855paymax0hd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT ukti43mpb7v4b6t855paymax0hd UNIQUE (cpf_cnpj);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: lawsuit fk432kqggtc666k8o2t07jpvd5u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lawsuit
    ADD CONSTRAINT fk432kqggtc666k8o2t07jpvd5u FOREIGN KEY (lawyer_id) REFERENCES public.lawyer(id);


--
-- Name: lawsuit fk4eq92e99fsmm824ty1fy1ch58; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lawsuit
    ADD CONSTRAINT fk4eq92e99fsmm824ty1fy1ch58 FOREIGN KEY (counter_part_person_id) REFERENCES public.person(id);


--
-- Name: documents fk573dr50v2rg9ar8cx8wdpq1by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fk573dr50v2rg9ar8cx8wdpq1by FOREIGN KEY (contract_id) REFERENCES public.contract(id);


--
-- Name: contract fkbh5xttovi777emshc9yekt5nx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT fkbh5xttovi777emshc9yekt5nx FOREIGN KEY (contractor_person_id) REFERENCES public.person(id);


--
-- Name: documents fkddiccjn0gmjbg272h84pyu8p8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fkddiccjn0gmjbg272h84pyu8p8 FOREIGN KEY (lawsuit_id) REFERENCES public.lawsuit(id);


--
-- Name: contract fkhaa38ndodg0x5dvejdiyejyy5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT fkhaa38ndodg0x5dvejdiyejyy5 FOREIGN KEY (contracted_person_id) REFERENCES public.person(id);


--
-- Name: lawyer fkhvv85suhqu9mvdmdbwnb9tast; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lawyer
    ADD CONSTRAINT fkhvv85suhqu9mvdmdbwnb9tast FOREIGN KEY (id) REFERENCES public.person(id);


--
-- Name: refresh_token fkjtx87i0jvq2svedphegvdwcuy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fkjtx87i0jvq2svedphegvdwcuy FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: lawsuit fko6rnoyexdeculv0l5rbpruuo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lawsuit
    ADD CONSTRAINT fko6rnoyexdeculv0l5rbpruuo FOREIGN KEY (counter_part_lawyer_id) REFERENCES public.lawyer(id);


--
-- Name: lawsuit fkr84miu7xetui5ni2g3cvewysb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lawsuit
    ADD CONSTRAINT fkr84miu7xetui5ni2g3cvewysb FOREIGN KEY (person_id) REFERENCES public.person(id);


--
-- Name: contract_extension fkticuymgh5etuc9u2ojyrvvfuy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contract_extension
    ADD CONSTRAINT fkticuymgh5etuc9u2ojyrvvfuy FOREIGN KEY (contract_id) REFERENCES public.contract(id);

