package sisjuridico.carbocat.enums;

public enum Action {
    ACAO_CIVIL_PUBLICA,
    ACAO_CONSIGNATORIA,
    ACAO_DE_ALIMENTOS,
    ACAO_DE_COBRANCA,
    ACAO_DE_EXECUCAO,
    ACAO_DE_EXIGIR_CONTAS,
    ACAO_DE_INDENIZACAO,
    ACAO_DE_INVENTARIO,
    ACAO_DE_OBRIGACAO_DE_FAZER,
    ACAO_DE_REINTEGRACAO_DE_POSSE,
    ACAO_DE_USUCAPIAO,
    ACAO_DECLARATORIA,
    ACAO_MONITORIA,
    ACAO_POPULAR,
    ACAO_RESCISORIA,
    BUSCA_E_APREENSAO,
    CUMPRIMENTO_DE_SENTENCA,
    DIVORCIO_LITIGIOSO,
    EMBARGOS_A_EXECUCAO,
    EMBARGOS_DE_TERCEIRO,
    EXECUCAO_DE_TITULO_EXTRAJUDICIAL,
    EXECUCAO_FISCAL,
    HABEAS_CORPUS,
    MANDADO_DE_INJUNCAO,
    MANDADO_DE_SEGURANCA
}
