package sisjuridico.carbocat.enums;

public enum InitialOrganization {
    PRIMEIRO_GRAU,
    SEGUNDO_GRAU,
    TRIBUNAL_SUPERIOR,
    JUIZADO_ESPECIAL,
    TURMA_RECURSAL,
    TURMA_REGIONAL_DE_UNIFORMIZACAO,
    TURMA_NACIONAL_DE_UNIFORMIZACAO,
    VARA_CIVEL,
    VARA_CRIMINAL,
    VARA_DE_FAMILIA,
    VARA_DA_INFANCIA_E_JUVENTUDE,
    VARA_DA_FAZENDA_PUBLICA,
    VARA_DE_EXECUCOES_FISCAIS,
    VARA_DE_EXECUCOES_PENAIS,
    VARA_DO_TRABALHO,
    ZONA_ELEITORAL,
    AUDITORIA_MILITAR,
    COMARCA,
    FORO,
    SECAO_JUDICIARIA,
    SUBSECAO_JUDICIARIA
}
