ALTER TABLE public.documents
    ADD COLUMN created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN size_bytes bigint NOT NULL DEFAULT 0;

ALTER TABLE public.documents
    ALTER COLUMN created_at DROP DEFAULT,
    ALTER COLUMN size_bytes DROP DEFAULT;

CREATE TABLE public.evento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo varchar(150) NOT NULL,
    tipo varchar(40) NOT NULL,
    data date NOT NULL,
    hora time,
    responsavel varchar(255),
    nota varchar(1000),
    contract_id bigint,
    lawsuit_id bigint,
    CONSTRAINT ck_evento_contract_or_lawsuit CHECK ((contract_id IS NULL) OR (lawsuit_id IS NULL)),
    CONSTRAINT fk_evento_contract FOREIGN KEY (contract_id) REFERENCES public.contract(id) ON DELETE SET NULL,
    CONSTRAINT fk_evento_lawsuit FOREIGN KEY (lawsuit_id) REFERENCES public.lawsuit(id) ON DELETE SET NULL
);

CREATE INDEX idx_evento_data_hora ON public.evento(data, hora);
CREATE INDEX idx_documents_created_at ON public.documents(created_at DESC);
